[tox]
envlist = py38, py39, py310, py311, py312, flake8

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 hiposa

[testenv]
extras = dev
commands =
    pytest --basetemp={envtmpdir}
